# Generated by Django 4.2 on 2025-06-21 19:22

from django.db import migrations, models
import sponsorship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=sponsorship.models.generate_session_id, max_length=6, unique=True)),
                ('host_device_id', models.CharField(max_length=255)),
                ('client_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=sponsorship.models.default_expiry)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
